### ISSUE TITLE
subsetRep()

### ISSUE THREAD

**Issue by zhongyi960403** [rje42/ADMGs2#1]
subsetRep(graphCr("x1 - x2",  "x1 - x4",  "x2 - x5", "x4 - x5", "x1 -> x3",   "x2 -> x3",  "x4 -> x3", "x5 -> x3 "))
Error in grp(graph, v, etype = "bidirected", dir = 0, sort = sort) : 
  Invalid values of v

**Comment by rje42** [comment]
Now fixed, you'll need the latest version of `MixedGraphs` to get it to work.

Thanks!
