### ISSUE TITLE
subsetRep()

### ISSUE THREAD

**Issue by zhongyi960403** [rje42/ADMGs2#2]
subsetRep(graphCr("x1 - x2", "x1 - x4", "x2 - x5", "x4 - x5", "x1 -> x3", "x2 -> x3", "x4 -> x3", "x5 -> x3 "))
works fine but

subsetRep(graphCr("x1 - x2", "x1 - x4", "x2 - x5", "x4 - x5", "x1 -> x3", "x2 -> x3", "x4 -> x3", "x5 -> x3 ",mode="adjMatrix))
Error in parents[[i]] : subscript out of bounds

My previous codes edit graph by using adjMatrix so I need subsetRep to work well when mode="adjMatrix". Thanks!

**Comment by rje42** [comment]
Fixed in `MixedGraphs` again!  Thanks.
