### ISSUE TITLE
Error in fitADMG()

### ISSUE THREAD

**Issue by zhongyi960403** [rje42/ADMGs2#3]
```
graph <- graphCr("6 - 4 - 5 - 7 - 6","2 -> 1")
fitADMG(gss, graph, r=FALSE)
```
Error in loglin(dat2, clq, fit = TRUE, eps = sqrt(.Machine$double.eps),  : 
  negative length vectors are not allowed

**Comment by rje42** [comment]
Thanks - now fixed. 

The problem was with the `headsTails()` function, and then the mapping of cliques in `fitUG()`.
