### ISSUE TITLE
Errors in subsetRep()

### ISSUE THREAD

**Issue by zhongyi960403** [rje42/ADMGs2#4]
```
G <- graphCr("1 - 4 - 6 - 7 - 1 -> 2","7 -> 5",mode="adjMatrix")
subsetRep(G,max_size=3,sort=3)
Error in parents[[i]] : subscript out of bounds
```
It works when mode is "adjList"(default)

**Comment by rje42** [comment]
Thanks! Solved that immediate problem: it was a bug in `MixedGraphs`, so you'll need to install the latest version of that.
